### ISSUE TITLE
etcd autoscale setup

### ISSUE THREAD

**Issue by billyteves** [coreos/kube-aws#239] opened 2017-01-12 05:02 UTC
I hope there is a chance to be have an autoscale for etcd. Similar to what high-availability of controller can do.

**Comment by mumoshu** [comment] 2017-01-12 10:44
Thanks for posting this!
Not sure it is feasible to auto-scale a metadata store like Etcd in kube-aws but I'll keep this open for a while to hear from the community.

**Comment by redbaron** [comment] 2017-01-12 17:52
I think it can be closed as duplicate of https://github.com/coreos/kube-aws/issues/27

**Comment by mumoshu** [comment] 2017-01-13 01:30
@redbaron AFAIK, no. #27 may utilize ASGs for discovery and recovery but not for auto-scaling.

**Comment by redbaron** [comment] 2017-01-13 08:27
https://github.com/coreos/kube-aws/issues/27 is about implementing etcd management in a proper way, which may or may not include autoscale, but it got to be decided in the context of that discussion.

**Comment by pieterlange** [comment] 2017-01-13 15:15
The primary intent of #27 is indeed for discovery and recovery, but i think you'd get "autoscaling" for free. I don't know why you'd want such a critical part of the system to be autoscaling - in my experience the only reason for having multiple etcd nodes is for concistency, not at all performance. (it could be argued that adding more nodes makes things slower)

Sorry for the lack of progress on #27 - i'm still too busy to work on the poc and i have to digest the changes in this repo. Things have been moving fast. :)

**Comment by billyteves** [comment] 2017-01-15 08:33
My idea here is to have an auto-scaling group setup, wherein when one etcd instance failed/terminated/gone, another instance will pop up and then join to the etcd cluster. Yup Im also on the consistency actually rather performance. As long as the users will not worry the sudden collapse of an etcd instance, I think there will be a reassurance that the cluster can recover, automatically.

**Comment by mumoshu** [comment] 2017-01-16 02:47
Ah, then we can close this in favor of #27, right?
I had originally thought of something like "Autoscale/Automatically **scale-out** etcd cluster by automatically **scaling up** all the etcd nodes one by one without downtime to improve both write/read qps a etcd cluster can serve" for "autoscaling of etcd", which didn't seem to be something covered by #27.

**Comment by billyteves** [comment] 2017-01-16 23:56
I actually haven't check yet the #27 , if it is also included in #27 , I think we can close this. With your idea above @mumoshu , I think it would be great to have that kind of feature also in the future! Right now, the etcd part of high-availability setup is probably the weakest point for me, since there is still a possibility that instance may go down for sometime and there is no auto-scaling configured yet. User might take a manual task to add another instance and join it to the etcd cluster. I think once we have added this, devops will have a higher confidence in the setup.  thank you guys for making kube-aws awesome!. :)

**Comment by mumoshu** [comment] 2017-02-01 07:32
@billyteves Thanks for the comment!
Yes, I agree to every point and that's what I believe to be already included in #27.

**Closed by mumoshu** 2017-02-01 07:32 UTC
Labels: waiting for community feedback
