### ISSUE TITLE
Restarting kubelet forgets CNI state and reuses pod IPs

### ISSUE THREAD

**Issue by groner** [coreos/kube-aws#60] opened 2016-11-15 16:24 UTC
Previously coreos/coreos-kubernetes#755.

---

I have a cluster built with kube-aws-v0.8.3 and hyperkube-v1.4.5_coreos.0.

While trying to shake out an EBS volume mount problem on one of the minions, I restarted kubelet using `systemctl restart kubelet` on that host.  After the restart, it seems active pod IPs are getting reassigned.

```
core@ip-10-0-48-65 ~ $ journalctl | grep Determined.pod.ip 
Nov 07 22:31:20 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1107 22:31:20.320259    1706 docker_manager.go:2162] Determined pod ip after infra change: "kubernetes-dashboard-v1.4.1-wbo4r_kube-system(e6f3c346-a539-11e6-b0a2-06cd71806322)": "10.2.37.2"
Nov 07 22:31:20 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1107 22:31:20.549372    1706 docker_manager.go:2162] Determined pod ip after infra change: "kube-dns-v20-83ltq_kube-system(e6f4151f-a539-11e6-b0a2-06cd71806322)": "10.2.37.3"
Nov 07 22:31:20 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1107 22:31:20.608372    1706 docker_manager.go:2162] Determined pod ip after infra change: "heapster-v1.2.0-3646253287-1nj4n_kube-system(e6f4a391-a539-11e6-b0a2-06cd71806322)": "10.2.37.4"
Nov 07 22:31:36 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1107 22:31:36.128090    1706 docker_manager.go:2162] Determined pod ip after infra change: "heapster-v1.2.0-4088228293-q7nnq_kube-system(f0f4afa3-a539-11e6-b0a2-06cd71806322)": "10.2.37.5"
Nov 08 16:25:09 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1108 16:25:09.883226    1706 docker_manager.go:2162] Determined pod ip after infra change: "sterling-etcd-txvpf_default(cca2979b-a5cf-11e6-b0a2-06cd71806322)": "10.2.37.6"
Nov 08 16:28:54 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: I1108 16:28:54.127206    1706 docker_manager.go:2162] Determined pod ip after infra change: "sterling-etcd-2180225719-92xfx_default(6639c26d-a5d0-11e6-b0a2-06cd71806322)": "10.2.37.7"
[kubelet restart happens here]
Nov 08 20:43:38 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 20:43:38.716862   10530 docker_manager.go:2162] Determined pod ip after infra change: "sterling-etcd-2180225719-g6a5e_default(3c3850ff-a5ee-11e6-b0a2-06cd71806322)": "10.2.37.2"
Nov 08 21:03:54 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 21:03:54.104308   10530 docker_manager.go:2162] Determined pod ip after infra change: "haproxy-init-3189418104-vd5cn_default(dafe6a15-a5f6-11e6-b0a2-06cd71806322)": "10.2.37.3"
Nov 08 21:05:21 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 21:05:21.789693   10530 docker_manager.go:2162] Determined pod ip after infra change: "bash_default(0f4309fa-a5f7-11e6-b0a2-06cd71806322)": "10.2.37.4"
Nov 08 21:06:29 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 21:06:29.234689   10530 docker_manager.go:2162] Determined pod ip after infra change: "haproxy-init_default(3778d187-a5f7-11e6-b0a2-06cd71806322)": "10.2.37.5"
Nov 08 21:11:11 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 21:11:11.348714   10530 docker_manager.go:2162] Determined pod ip after infra change: "haproxy-init_default(dfa25588-a5f7-11e6-b0a2-06cd71806322)": "10.2.37.6"
Nov 08 21:58:29 ip-10-0-48-65.ec2.internal kubelet-wrapper[10530]: I1108 21:58:29.094155   10530 docker_manager.go:2162] Determined pod ip after infra change: "sterling-etcd-2180225719-sj3a3_default(7a7ea798-a5fe-11e6-b0a2-06cd71806322)": "10.2.37.7"
```

This message from the time o the restart seems to explain the problem:
```
Nov 07 22:31:20 ip-10-0-48-65.ec2.internal kubelet-wrapper[1706]: 2016/11/07 22:31:20 Error retriving last reserved ip: Failed to retrieve last reserved ip: open /var/lib/cni/networks/podnet/last_reserved_ip: no such file or directory
```

**Comment by pieterlange** [comment] 2016-11-15 18:21
Can you try to run replicate this issue against the [latest release](https://github.com/coreos/kube-aws/releases/tag/v0.9.1-rc.2)?

Also, are you running with flannel as CNI plugin or are you using the builtin?

**Comment by groner** [comment] 2016-11-15 18:38
@aaronlevy Thanks for the heads up about the repository change.

**Comment by groner** [comment] 2016-11-15 19:08
Hi @pieterlange,

> Can you try to run replicate this issue against the latest release?

I will give the latest release a try.

> Also, are you running with flannel as CNI plugin or are you using the builtin?

I'm not sure exactly what this means.  I am specifying an existing VPC and route table, but otherwise I don't think I've changed anything from the default networking configuration.

I deleted the cloudformation stack, but I still have the template file.  From it I can see the userdata contains a write_files entry with `path: /etc/kubernetes/cni/net.d/10-flannel.conf` and the image id is ami-4d795c5a, which has the name CoreOS-stable-1185.3.0-hvm.

I do have some userdata changes that add a few scripts and unit files, but I can parse the resulting yaml with pyyaml and see the expected entries, so I don't think there's any interference there.

**Comment by mumoshu** [comment] 2016-11-17 01:38
@groner @pieterlange Thanks for starting the discussion.

Honestly, I'm afraid that I don't have enough knowledge around CNI to tackle this issue!

Hello @tomdee, would you mind if I ask for your help to locate where to fix?

We're observing `Failed to retrieve last reserved ip` errors emitted from kubelet, which may/may not be causing active pod IPs to be reused. However, I'm not sure if that's really an issue/how we can fix/where to read the code/etc. Any piece of advice is welcome 🙏 

@groner I'm not yet sure if the `Determined pod ip after infra change` message means an "active" pod ip is actually reused.

Restarting `kubelet` alone won't actually restart k8s pods(or at least underlying docker containers), right? If so, there might be no need to bring up "another pods" to reused active IPs, in the first place. In other words, active IPs can't be reused like that if restarting kubelet doesn't actually bring up new pods.

If that's the case, I guess the `Determined pod ip after infra change` message is just saying that kubelet+cni successfuly "restored" a running pod's state e.g. an ip assigned to pod, not reused an ip.

**Comment by mumoshu** [comment] 2016-11-17 01:47
@groner Whether my assumption is true or not, I believe the `Error retriving last reserved ip: Failed to retrieve last reserved ip: open /var/lib/cni/networks/podnet/last_reserved_ip: no such file or directory` error should be fixed.

[Your idea of how to fix it](https://github.com/coreos/coreos-kubernetes/issues/755#issuecomment-259281721) seems good but I'm not yet sure how kubelet and/or cni are assuming `/var/lib/cni` to be configured.
We need to survey how it should be configured in the first place.

**Comment by mumoshu** [comment] 2016-11-17 03:53
* Should the `/var/lib/cni/networks/your-network-name` directory persist between kubelet restarts?
  * It seems to that we're naming our network `podnet` in https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-worker#L350 hence `/var/lib/cni/networks/podnet` (also see [cni source](https://github.com/containernetworking/cni/blob/master/plugins/ipam/host-local/backend/disk/backend.go#L27))
  * I've seen several references to directories like that in the wild e.g.
    * https://github.com/cdxvirt/k8sup/blob/master/entrypoint.sh#L597
* [CNI is hard-coded with /var/lib/cni/networks as the default data dir](https://github.com/containernetworking/cni/blob/master/plugins/ipam/host-local/backend/disk/backend.go#L27)
* [CNI itself seems to store last_reserved_ip each time new ip is registered](https://github.com/containernetworking/cni/blob/master/plugins/ipam/host-local/backend/disk/backend.go#L50)
  * Is it an enough reason to persist the data dir for CNI? (Maybe)
* Seems different but relevant issues:
  * https://github.com/kubernetes/kubernetes/issues/34278

**Comment by groner** [comment] 2016-11-17 06:07
Hi @mumoshu,

The `Determined pod ip after infra change` message occurs before I restarted the kubelet.  I'm guessing it comes from the initial creation of the pods.  I don't think any conflicts occur until the kubelet needs to allocate an IP for a new pod.  The messages that occur after the restart were caused by me, creating more pods.

I had some networking difficulties (sometimes I could connect to the pod, other times the connection was refused) that led to this investigation.  I tried to make my report concise, but I probably left out too much.  Below is a more thorough investigation, which I hope will clarify things further.  

---
This is a new cluster, created using kube-aws-v0.9.1-rc.2 and hyperkube-v1.4.6_coreos.0.
```
# pods on the controller removed for brevity here
: kai@cakepile kube19; kubectl get pod --all-namespaces -o wide
NAMESPACE     NAME                                                 READY     STATUS    RESTARTS   AGE       IP            NODE
[pods on the controller removed for brevity here]
kube-system   heapster-v1.2.0-4088228293-2d6hf                     2/2       Running   0          5m        10.2.37.5     ip-10-0-48-181.ec2.internal
kube-system   kube-dns-v20-hmxst                                   3/3       Running   0          6m        10.2.37.2     ip-10-0-48-181.ec2.internal
kube-system   kube-proxy-ip-10-0-48-181.ec2.internal               1/1       Running   0          5m        10.0.48.181   ip-10-0-48-181.ec2.internal
kube-system   kubernetes-dashboard-v1.4.1-t4bw3                    1/1       Running   0          6m        10.2.37.4     ip-10-0-48-181.ec2.internal
```

```
ip-10-0-48-181 ~ # rkt list
UUID		APP		IMAGE NAME					STATE	CREATED		STARTED		NETWORKS
[flannel pods removed for brevity]
59aec852	hyperkube	quay.io/coreos/hyperkube:v1.4.6_coreos.0	running	7 minutes ago	7 minutes ago	
ip-10-0-48-181 ~ # ls -l /var/lib/rkt/pods/run/59aec852-4466-4058-8d88-01d8f97241e2/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/cni/networks/podnet
total 32
-rw-r--r--. 1 root root 64 Nov 17 04:56 10.2.37.2
-rw-r--r--. 1 root root 64 Nov 17 04:56 10.2.37.4
-rw-r--r--. 1 root root 64 Nov 17 04:56 10.2.37.5
-rw-r--r--. 1 root root  9 Nov 17 04:56 last_reserved_ip
```

Kicking the kubelet.
```
ip-10-0-48-181 ~ # systemctl restart kubelet
```

Run a busybox pod.  It gets assigned the same IP as kube-dns.
```
: kai@cakepile kube19; kubectl run --restart=Never --image busybox -it shell -- sh
Waiting for pod default/shell to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
/ # ip addr show eth0
3: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 8951 qdisc noqueue 
    link/ether 0a:58:0a:02:25:02 brd ff:ff:ff:ff:ff:ff
    inet 10.2.37.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::6c72:d3ff:fe6e:d2d5/64 scope link tentative flags 08 
       valid_lft forever preferred_lft forever
```

Notice shell and kube-dns are both assigned 10.2.37.2.
```
: kai@cakepile kube19; kubectl get pod --all-namespaces -o wide 
NAMESPACE     NAME                                                 READY     STATUS    RESTARTS   AGE       IP            NODE
[pods on the controller removed for brevity here]
default       shell                                                1/1       Running   0          31s       10.2.37.2     ip-10-0-48-181.ec2.internal
kube-system   heapster-v1.2.0-4088228293-2d6hf                     2/2       Running   0          22m       10.2.37.5     ip-10-0-48-181.ec2.internal
kube-system   kube-dns-v20-hmxst                                   2/3       Running   0          23m       10.2.37.2     ip-10-0-48-181.ec2.internal
kube-system   kube-proxy-ip-10-0-48-181.ec2.internal               1/1       Running   0          21m       10.0.48.181   ip-10-0-48-181.ec2.internal
kube-system   kubernetes-dashboard-v1.4.1-t4bw3                    1/1       Running   0          23m       10.2.37.4     ip-10-0-48-181.ec2.internal
```

Queries to the kube-dns pod timeout if the request hits the busybox pod instead of the real kube-dns.
```
ip-10-0-48-181 ~ # dig @10.2.37.2 kubernetes.default.svc.cluster.local
; <<>> DiG 9.10.2-P4 <<>> @10.2.37.2 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
ip-10-0-48-181 ~ # rkt list
UUID		APP		IMAGE NAME					STATE	CREATED		STARTED		NETWORKS
[flannel pods removed for brevity]
59aec852	hyperkube	quay.io/coreos/hyperkube:v1.4.6_coreos.0	exited	9 minutes ago	9 minutes ago	
d2b342df	hyperkube	quay.io/coreos/hyperkube:v1.4.6_coreos.0	running	3 seconds ago	2 seconds ago	
ip-10-0-48-181 ~ # ls -l /var/lib/rkt/pods/run/d2b342df-84fa-43d2-b1a7-1358858485a8/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/cni/networks/podnet
total 16
-rw-r--r--. 1 root root 64 Nov 17 05:03 10.2.37.2
-rw-r--r--. 1 root root  9 Nov 17 05:03 last_reserved_ip
```

After deleting the busybox pod, the kube-dns pod is responsive again.
```
ip-10-0-48-181 ~ # dig @10.2.37.2 kubernetes.default.svc.cluster.local

; <<>> DiG 9.10.2-P4 <<>> @10.2.37.2 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5385
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 5	IN A	10.3.0.1

;; Query time: 0 msec
;; SERVER: 10.2.37.2#53(10.2.37.2)
;; WHEN: Thu Nov 17 05:39:54 UTC 2016
;; MSG SIZE  rcvd: 81
```

**Comment by mumoshu** [comment] 2016-11-17 06:45
@groner I appreciate your concise, detailed report, thank you 🙇 

I now believe this is a pretty critical issue we've overlooked for a long time, which should be fixed shortly.
No one wants to encounter instability in communication between pods like this after a random kubelet restart!

**Comment by mumoshu** [comment] 2016-11-17 07:04
I'm wondering why /var/lib/cni/networks is not mentioned in http://kubernetes.io/docs/admin/network-plugins/#cni at all.

Maybe that's because only folks running containerized hyperkube like us are being affected by this issue?

**Comment by mumoshu** [comment] 2016-11-17 07:24
Hello @dghubble!

Just curious/wanted to notice but have you ever encountered this issue(=active IPs are reassigned/newly created pods get assigned in-use ips after restarting kubelet) in coreos-kubernetes?

It seems to me that we have to mount host's `/var/lib/cni/networks` to a kubelet container to avoid this issue.

AFAICS, both:

* [kubelet-wrapper coming from CoreOS](https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper#L65-L78)
* [cloud-config in a coreos-baremetal example](https://github.com/coreos/coreos-baremetal/blob/91d42b9e1f00603a596b24b4e29fa72c73e267fd/examples/ignition/k8s-worker.yaml#L62-L65)

don't seem to mount it.

So I guess this issue may also affect coreos-baremetal and even other kubernetes clusters running kubelets through kubelet-wrapper.

**Comment by mumoshu** [comment] 2016-11-17 08:24
It turns out that the flannel adapter(?) for CNI also assume a directory named `/var/lib/cni/flannel` to exist for persisting its state.
https://github.com/containernetworking/cni/blob/56032390fe659c95360ca629a66f7ab32672651b/plugins/meta/flannel/flannel.go#L40

FWIW, let me mount the umbrella directory `/var/lib/cni` to kublet containers and see it works.

**Comment by mumoshu** [comment] 2016-11-17 09:14
@groner Still running E2E tests but would you mind trying https://github.com/coreos/kube-aws/pull/64?

Running `git clone` to an appropriate directory under `$GOPATH` and then `glide install`, `./build` will produce a `bin/kube-aws` binary with the fix.

Also I'll cut 0.9.1-rc.3 once E2E passed.

**Comment by mumoshu** [comment] 2016-11-17 12:20
Just released 0.9.1-rc.3 with the fix.

FWIW I've tried to reproduce the issue with calico-enabled cluster(=`useCalico: true` in cluster.yaml. Maybe @groner you're using cni+flannel=`useCalico: false`, right?) because it was just a bit easier for me than the `useCalico: false` one as it is semi-automated.

* Pods named `shell*` are created before `sudo systemctl restart kubelet.service`.
* Pods named `ls*` are created after restarting.

```
$ kubectl get po --all-namespaces -o wide --show-all | grep 143
default         ls                                                                      0/1       ContainerCannotRun   0          1m        10.2.83.106   ip-10-0-0-143.ap-northeast-1.compute.internal
default         ls1                                                                     0/1       Completed            0          1m        10.2.83.107   ip-10-0-0-143.ap-northeast-1.compute.internal
default         ls2                                                                     0/1       Completed            0          57s       10.2.83.108   ip-10-0-0-143.ap-northeast-1.compute.internal
default         ls3                                                                     0/1       Completed            0          51s       <none>        ip-10-0-0-143.ap-northeast-1.compute.internal
default         ls4                                                                     0/1       Completed            0          44s       10.2.83.110   ip-10-0-0-143.ap-northeast-1.compute.internal
default         ls5                                                                     0/1       Completed            0          37s       10.2.83.111   ip-10-0-0-143.ap-northeast-1.compute.internal
default         shell                                                                   0/1       Completed            0          5m        10.2.83.101   ip-10-0-0-143.ap-northeast-1.compute.internal
default         shell2                                                                  0/1       Completed            0          3m        10.2.83.102   ip-10-0-0-143.ap-northeast-1.compute.internal
default         shell3                                                                  0/1       Completed            0          3m        10.2.83.103   ip-10-0-0-143.ap-northeast-1.compute.internal
default         shell4                                                                  0/1       Completed            0          3m        10.2.83.104   ip-10-0-0-143.ap-northeast-1.compute.internal
default         shell5                                                                  0/1       Completed            0          2m        10.2.83.105   ip-10-0-0-143.ap-northeast-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-143.ap-northeast-1.compute.internal                1/1       Running              0          2h        10.0.0.143    ip-10-0-0-143.ap-northeast-1.compute.internal
```

As you can see, each pod has an unique ip! Good so far.

**Comment by mumoshu** [comment] 2016-11-17 12:43
Now provisioning a cluster via v0.9.1-rc.3 with `useCalico: false`.
I'll try to reproduce the issue in the cluster tomorrow.

**Comment by groner** [comment] 2016-11-17 15:03
@mumoshu It looks good to me.

I created a cluster with the v0.9.1-rc.3 release and `useCalico: false`.  I can restart the kubelet and then start new pods without any of the previous IP conflicts.

**Comment by mumoshu** [comment] 2016-11-17 22:57
Finished testing with `useCalico: false`.

* Pods named `before*` are created before sudo systemctl restart kubelet.service.
* Pods named `after*` are created after restarting.

```
$ kubectl get po -o wide --all-namespaces | grep 244
default       after-1                                                                 1/1       Running   0          30s       10.2.45.128   ip-10-0-0-244.ap-northeast-1.compute.internal
default       after-2                                                                 1/1       Running   0          30s       10.2.45.127   ip-10-0-0-244.ap-northeast-1.compute.internal
default       after-3                                                                 1/1       Running   0          29s       10.2.45.129   ip-10-0-0-244.ap-northeast-1.compute.internal
default       before-1                                                                1/1       Running   0          2m        10.2.45.124   ip-10-0-0-244.ap-northeast-1.compute.internal
default       before-2                                                                1/1       Running   0          1m        10.2.45.125   ip-10-0-0-244.ap-northeast-1.compute.internal
default       before-3                                                                1/1       Running   0          1m        10.2.45.126   ip-10-0-0-244.ap-northeast-1.compute.internal
kube-system   heapster-v1.2.0-4088228293-x1kh0                                        2/2       Running   0          8h        10.2.45.118   ip-10-0-0-244.ap-northeast-1.compute.internal
  info: 3 completed object(s) was(were) not shown in pods list. Pass --show-all to see all objects.

kube-system   kube-dns-v20-j4266                                                      3/3       Running   0          8h        10.2.45.119   ip-10-0-0-244.ap-northeast-1.compute.internal
kube-system   kube-proxy-ip-10-0-0-244.ap-northeast-1.compute.internal                1/1       Running   0          10h       10.0.0.244    ip-10-0-0-244.ap-northeast-1.compute.internal
kube-system   kubernetes-dashboard-v1.4.1-lib6p                                       1/1       Running   0          8h        10.2.45.120   ip-10-0-0-244.ap-northeast-1.compute.internal
```

```
$ sudo find /var/lib/cni
/var/lib/cni
/var/lib/cni/flannel
/var/lib/cni/flannel/5386aab965d0e910bc0f1e681991fa5218ab65180e550777d580317ef38c0911
/var/lib/cni/flannel/afe1c1b70efcdb0665a9d376a0b30c4ac019364e33557780d919c22e62040dc7
/var/lib/cni/flannel/d956484c77ce625d8bbae65cc1daf14daffdca13a137aa016d72f48c36241d12
/var/lib/cni/flannel/50f6cf2d870a65232c2ddda826d50d238cc0f08fc649230ca5a7e779e5bc9466
/var/lib/cni/flannel/8783481a79159c244a4a1a5ad1c9d80a203fad92dcd4b4625b0bb6e0eef6a14d
/var/lib/cni/flannel/13bc6ecacb0caa5f6386dd4b4d7ec55f574b7fbde9b4df28856643d9445b0c76
/var/lib/cni/flannel/1d53d6320594484570b3828e1b8ec54d2a570e22389f9c22566c9baaa2b24634
/var/lib/cni/flannel/bbdd7277dfd7110b2cbc609a5526b930d4dec77c7ef4606ef573b24247477d23
/var/lib/cni/flannel/bdb5d3d063888e42f1f6f652f02b433fc733e7b0a73f0140811a6883720aa304
/var/lib/cni/networks
/var/lib/cni/networks/podnet
/var/lib/cni/networks/podnet/10.2.45.127
/var/lib/cni/networks/podnet/10.2.45.129
/var/lib/cni/networks/podnet/10.2.45.128
/var/lib/cni/networks/podnet/10.2.45.119
/var/lib/cni/networks/podnet/last_reserved_ip
/var/lib/cni/networks/podnet/10.2.45.120
/var/lib/cni/networks/podnet/10.2.45.118
/var/lib/cni/networks/podnet/10.2.45.124
/var/lib/cni/networks/podnet/10.2.45.125
/var/lib/cni/networks/podnet/10.2.45.126
```

```
$ sudo cat /var/lib/cni/networks/podnet/last_reserved_ip
10.2.45.129
```

**Comment by mumoshu** [comment] 2016-11-17 23:04
@groner LGTM, too 👍 

I'm closing this issue as resolved.

Thanks for locating the problem and providing the clear, detailed report @groner!
It really helped me understand the issue and narrowing down where to fix :bow:

**Closed by mumoshu** 2016-11-17 23:04 UTC
Labels: bug, help wanted
